/* Objective: Practice using an int *const where the pointed variable can change value, but the pointer remains "locked" to that address forever.
Instructions:
1. Declare int bank_balance = 1000; and int other_balance = 5000;.
2. Create a constant pointer to the balance: int *const ptr_account = &bank_balance;.
3. Change the balance value through the pointer: *ptr_account = 1200; (Check that it works!).
4. Try to point to another account: ptr_account = &other_balance; and comment on the error generated by the compiler. */

#include <stdio.h>

int main(void)
{
    int bank_balance = 1000;
    int other_balance = 5000;

    // Constant pointer to a mutable int
    int *const ptr_account = &bank_balance;

    printf("Initial balance: R$ %d\n", *ptr_account);

    // Allowed: changes the value stored at the address
    *ptr_account = 1200;

    printf("Updated balance: R$ %d\n", bank_balance);

    // Not allowed: tries to change the address held by the pointer
    // ptr_account = &other_balance;

    return 0;
}