/* Objective: Understand the classic syntax of register in loop control variables.
Instructions:
1. Create a loop control variable with the specifier: register int i;.
2. Set up a for loop (i = 0; i < 5; i++) printing the value of i.
3. Then, try to obtain the memory address of i: int *p = &i;.
4. Observe the compilation error generated by C, comment out the incorrect line so the code compiles again, and explain the reason in the comments. */

#include <stdio.h>

int main(void) {
    register int i;

    for (i = 0; i < 5; i++) {
        printf("i = %d\n", i);
    }

    /*
    int *p = &i;

    ERROR:
    A variable declared with "register" cannot have its address
    obtained using the & operator.

    The register specifier indicates that the variable will be heavily used
    and suggests to the compiler that it may be kept in a processor register
    instead of memory.

    Therefore, the C language explicitly forbids using &i when i has been
    declared as register.

    The line was commented out to allow the program to compile.
    */

    return 0;
}